name: "lint and test"
on: push

jobs:
  lint-and-test:
    name: run tests
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.5.1
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          apt-get update
          apt-get -y install python3-dev
          apt-get -y install python3-pip
          pip3 install tox
          tox -e lint,test
